/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.Render;
import controlador.ConexionDB;
import modelo.Usuario;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author johna
 */
public class page2 extends javax.swing.JPanel {

    /**
     * Creates new form page2
     */
    public page2() {
        initComponents();
        txtID.setVisible(false);
        MostrarTablaUsuario();

    }

     public void MostrarTablaUsuario(){
          
        tablausuarios.setDefaultRenderer(Object.class, new Render());  
        
        JButton btn1 = new JButton("Editar");
        btn1.setName("ed");
        JButton btn2 = new JButton("Eliminar");
        btn2.setName("el");
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("DOCUMENTO");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("CONTRASEÑA");
        modelo.addColumn("ROL");
        modelo.addColumn("ESTADO");
        modelo.addColumn("EDITAR");
        modelo.addColumn("ELIMINAR");
        tablausuarios.setModel(modelo);
        
        ConexionDB co=new ConexionDB();
        ArrayList<Usuario> Lista=co.ListarUsuario();
        Object datos[]=new Object[8];
        for (Usuario usuario: Lista) {
            datos[0]=usuario.getId();
            datos[1]=usuario.getDocumento();
            datos[2]=usuario.getNombre();
            datos[3]=usuario.getContrasena();
            datos[4]=usuario.getRol();
            datos[5]=usuario.getEstado();
            datos[6]= btn1;
            datos[7]= btn2;
            modelo.addRow(datos);
        }
        this.tablausuarios.setDefaultRenderer(Object.class, new Render());
        tablausuarios.setModel(modelo);
        
        this.tablausuarios.setRowHeight(35);
         TableColumn columna_aux = this.tablausuarios.getColumn("EDITAR");
         columna_aux.setPreferredWidth(80);
         TableColumn columna_aux1 = this.tablausuarios.getColumn("ID");
         columna_aux1.setPreferredWidth(20);
        
         TableColumn columna_aux2 = this.tablausuarios.getColumn("ELIMINAR");
         columna_aux2.setPreferredWidth(100);
         
        btn1.setBackground(new java.awt.Color(229, 190, 1));
        btn1.setFont(new java.awt.Font("Segoe UI", 0, 14));
        
        btn2.setBackground(new java.awt.Color(203, 50, 52));
        btn2.setFont(new java.awt.Font("Segoe UI", 0, 14));
        btn2.setForeground(new java.awt.Color(255, 255, 255));
    }
     
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtdocumento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcontrasena = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        listaestado = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        listarol = new javax.swing.JComboBox<>();
        btnactualizar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablausuarios = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtdocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdocumentoActionPerformed(evt);
            }
        });
        txtdocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdocumentoKeyTyped(evt);
            }
        });
        jPanel2.add(txtdocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 302, 38));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 20)); // NOI18N
        jLabel1.setText("Empleados");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 7, 176, 29));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("En este panel podras gestionar los datos de los empleados");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 42, 302, 23));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Documento");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 116, 22));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Nombre");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 302, 22));

        txtcontrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontrasenaActionPerformed(evt);
            }
        });
        jPanel2.add(txtcontrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 302, 38));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Rol");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 302, 22));

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 302, 38));

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Contraseña");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 302, 22));

        listaestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        listaestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaestadoActionPerformed(evt);
            }
        });
        jPanel2.add(listaestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 302, -1));

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Estado");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 302, 22));

        listarol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado" }));
        listarol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarolActionPerformed(evt);
            }
        });
        jPanel2.add(listarol, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 302, -1));

        btnactualizar.setBackground(new java.awt.Color(49, 211, 49));
        btnactualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnactualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnactualizar.setText("Actualizar");
        btnactualizar.setEnabled(false);
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 111, 42));

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 111, 42));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel2.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 13, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Ingrese el No de documento sin espacios ni caracteres especiales");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        tablausuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablausuarios.setEnabled(false);
        tablausuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablausuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablausuarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablausuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablausuariosMouseClicked
        // TODO add your handling code here:
        int clic_tabla =0;
        clic_tabla = this.tablausuarios.rowAtPoint(evt.getPoint());
        
        String idusuario = ""+tablausuarios.getValueAt(clic_tabla, 0);
        String documento = ""+tablausuarios.getValueAt(clic_tabla, 1);
        String nombre = ""+tablausuarios.getValueAt(clic_tabla, 2);
        String contrasena = ""+tablausuarios.getValueAt(clic_tabla, 3);
        String rol = ""+tablausuarios.getValueAt(clic_tabla, 4);
        String estado = ""+tablausuarios.getValueAt(clic_tabla, 5);
        
                
        int column = tablausuarios.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tablausuarios.getRowHeight();
        
        if (row < tablausuarios.getRowCount() && row >=0 && column < tablausuarios.getColumnCount() && column >=0) {
            Object value = tablausuarios.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton)value).doClick();
                JButton boton = (JButton) value;
                
                if (boton.getName().equals("ed")) {
                    btnactualizar.setEnabled(true);
                    jButton2.setEnabled(false);
                    txtID.setText(idusuario);
                    txtdocumento.setText((documento));
                    txtnombre.setText(nombre);
                    txtcontrasena.setText(contrasena);
                    listarol.setSelectedItem(rol);
                    listaestado.setSelectedItem(estado);
        
                }
                 if (boton.getName().equals("el")) {
                   btnactualizar.setEnabled(false);
                   jButton2.setEnabled(true);
                   txtdocumento.setText(null);
                   txtnombre.setText(null);
                   txtcontrasena.setText(null);
                   ConexionDB co=new ConexionDB();
                   int respuesta=co.Elusuario(idusuario);
                   if (respuesta==1) {
                       JOptionPane.showMessageDialog(null, "Usuario eliminado correctamente");
                        MostrarTablaUsuario();

                   }else{
                       JOptionPane.showMessageDialog(null, "Error al eliminar usuario");
                   }           
                }
            }
        }
    }//GEN-LAST:event_tablausuariosMouseClicked

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String documento=txtdocumento.getText();
        String nombre=txtnombre.getText();
        String contrasena=txtcontrasena.getText();
        String rol= listarol.getSelectedItem().toString();
        String estado= listaestado.getSelectedItem().toString();
        if(documento.isEmpty()||contrasena.isEmpty()||nombre.isEmpty()){
            JOptionPane.showMessageDialog(this, "Favor de no dejar campos vacios");
        }else{
            ConexionDB co = new ConexionDB();
            int respuesta = co.Reusuario(documento,nombre, contrasena,rol,estado);
            if (respuesta==1) {
                JOptionPane.showMessageDialog(null, "Usuario registrado correctamente");
                txtdocumento.setText(null);
                txtnombre.setText(null);
                txtcontrasena.setText(null);
                MostrarTablaUsuario();
            }else{
                JOptionPane.showMessageDialog(null, "Error al registrar usuario");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        btnactualizar.setEnabled(false);
        jButton2.setEnabled(true);
        String documento=txtdocumento.getText();
        String nombre = txtnombre.getText();
        String contrasena =txtcontrasena.getText();
        String rol =(String) listarol.getSelectedItem();
        String estado =(String) listaestado.getSelectedItem();
        String idusuario = txtID.getText();
        if(documento.isEmpty()||contrasena.isEmpty()){
            JOptionPane.showMessageDialog(this, "Favor de no dejar campos vacios");
        }else{
            ConexionDB co=new ConexionDB();
            int respuesta=co.Acusuario(documento, nombre, contrasena, rol, estado, idusuario);

            if (respuesta==1) {
                JOptionPane.showMessageDialog(null, "Datos modificados");
                txtdocumento.setText(null);
                txtnombre.setText(null);
                txtcontrasena.setText(null);
                MostrarTablaUsuario();

            }else{
                JOptionPane.showMessageDialog(null, "Error al modificar");
            }   }
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void listarolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarolActionPerformed

    private void listaestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaestadoActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtcontrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontrasenaActionPerformed

    private void txtdocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdocumentoKeyTyped
        if (evt.getKeyChar()>=32 && evt.getKeyChar()<=47 || evt.getKeyChar()>=58 ) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo se permite el ingreso de numeros");
        }
    }//GEN-LAST:event_txtdocumentoKeyTyped

    private void txtdocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdocumentoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtdocumentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> listaestado;
    private javax.swing.JComboBox<String> listarol;
    private javax.swing.JTable tablausuarios;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtcontrasena;
    private javax.swing.JTextField txtdocumento;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
